services:
  airflow-postgres:
    image: postgres:15
    container_name: taxi_airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: taxi_airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    command: version

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: taxi_airflow_webserver
    depends_on:
      - airflow-postgres
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project/src
      AWS_PROFILE: zia-u-rahman.amerkhill
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/data
      - C:/Users/amerk/.aws:/home/airflow/.aws:ro
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: taxi_airflow_scheduler
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project/src
      AWS_PROFILE: zia-u-rahman.amerkhill
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/data
      - C:/Users/amerk/.aws:/home/airflow/.aws:ro
    command: scheduler